version: '3.5'

networks:
  prefect:
    name: prefect

services:
  postgres:
    image: postgres:15.2-alpine
    command:
      - postgres
      - -c
      - max_connections=150
    environment:
      POSTGRES_USER: ${PREFECT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PREFECT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PREFECT_POSTGRES_DB}
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d ${PREFECT_POSTGRES_DB} -U ${PREFECT_POSTGRES_USER} | grep "accepting connections" || exit 1
      timeout: 2s
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - prefect

  prefect-server:
    image: prefect-server:2.8.3
    command:
      - prefect
      - server
      - start
    ports:
      - 4200:4200
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./volumes/prefect:/root/.prefect
      - ./prefect/flows:/flows
    environment:
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_ORION_DATABASE_CONNECTION_URL: postgresql+asyncpg://${PREFECT_POSTGRES_USER}:${PREFECT_POSTGRES_PASSWORD}@postgres:5432/${PREFECT_POSTGRES_DB}
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: http://localhost:4200/api
    networks:
      - prefect

  prefect-agent:
    image: prefect-agent:2.8.3
    command:
      - prefect
      - agent
      - start
      - -q
      - default
    depends_on:
      prefect-server:
        condition: service_started
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_LOGGING_LEVEL: DEBUG
      DOCKER_HOST: unix://var/run/docker.sock
      GOOGLE_APPLICATION_CREDENTIALS: /.config/gcloud/application_default_credentials.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.gcp_keys/sa-prefect-agent_gcp_key.json:/.config/gcloud/application_default_credentials.json
    networks:
      - prefect