name: Build and Publish Docker prefect-agent

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/docker-prefect-agent.yaml"
      - "prefect/prefect-agent/**"

jobs:
  build-and-publish:
    name: Build and Publish Docker prefect-agent
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prefect/prefect-agent
    env:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_DEVOPS_SERVICE_ACCOUNT: ${{ secrets.GCP_DEVOPS_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_PYTHON_REPOSITORY_NAME: ${{ secrets.GCP_PYTHON_REPOSITORY_NAME }}
      GCP_DOCKER_REPOSITORY_NAME: ${{ secrets.GCP_DOCKER_REPOSITORY_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install keyring==23.13.1 keyrings.google-artifactregistry-auth==1.1.2

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_DEVOPS_SERVICE_ACCOUNT }}

      - name: "Setup Google Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Setup Artifact Registry
        run: |
          gcloud artifacts print-settings python --project=${GCP_PROJECT_ID} --repository=${GCP_PYTHON_REPOSITORY_NAME} --location=${GCP_REGION} > ~/.pypirc
          gcloud auth configure-docker

      - name: Download Python dependencies for Dockerfile
        run: |
          pip download -r ./requirements.txt --dest ./__pypackages__/ --extra-index-url https://${GCP_REGION}-python.pkg.dev/${GCP_PROJECT_ID}/${GCP_PYTHON_REPOSITORY_NAME}/simple

      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: prefect/prefect-agent
          push: true
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_DOCKER_REPOSITORY_NAME }}/prefect-agent:latest
