name: Python Package air-quality-lakehouse

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/python-package-lakehouse.yaml"
      - "spark/air-quality-lakehouse/**"

jobs:
  build-and-publish:
    uses: ./.github/workflows/python-package-template.yaml
    with:
      package_name: air-quality-lakehouse
      setup_path: spark/air-quality-lakehouse/
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
      GCP_DEVOPS_SERVICE_ACCOUNT: "${{ secrets.GCP_DEVOPS_SERVICE_ACCOUNT }}"
      GCP_PROJECT_ID: "${{ secrets.GCP_PROJECT_ID }}"
      GCP_PYTHON_REPOSITORY_NAME: "${{ secrets.GCP_PYTHON_REPOSITORY_NAME }}"
      GCP_REGION: "${{ secrets.GCP_REGION }}"
